### ISSUE TITLE
IgbSelect - binding doesn't work 

### ISSUE THREAD

**Issue by mddifilippo89** [IgniteUI/igniteui-blazor#116]
## Description  
Selection Changing options in IgbSelect do not update other components bound to the same item via @bind-value, but updating those items will update the IgbSelect. 

## Steps to reproduce  

1. Select a new option from the select dropdown, eg. "Apple"

## Result  
IgbInput and label do not update with "apple" and continue to be shown as "orange"

And Console Error:

System.NullReferenceException: Object reference not set to an instance of an object.
dotnet.native.8.0.2.tfnhmic6mv.js:8    at IgniteUI.Blazor.Controls.IgbSelect.<set_Change>b__102_0(IgbSelectItemComponentEventArgs args)
dotnet.native.8.0.2.tfnhmic6mv.js:8    at IgniteUI.Blazor.Controls.BaseRendererControl.<>c__DisplayClass188_0`1[[IgniteUI.Blazor.Controls.IgbSelectItemComponentEventArgs, IgniteUI.Blazor, Version=23.2.218.0, Culture=neutral, PublicKeyToken=null]].<SetHandler>b__0(Object sender, Object args)
dotnet.native.8.0.2.tfnhmic6mv.js:8    at IgniteUI.Blazor.Controls.BaseRendererControl.OnRaiseEvent(String name, String propertyName, String args)

## Expected result  
IgbInput and label update from "orange" to "apple".

## Attachments  
[overview.zip](https://github.com/IgniteUI/igniteui-blazor/files/15502280/overview.zip)

**Comment by mddifilippo89** [comment]
https://github.com/IgniteUI/igniteui-blazor/issues/111
