### ISSUE TITLE
ColumnVisibilityChanging/Changed events throw exception - cannot read properties of undefined 

### ISSUE THREAD

**Issue by mddifilippo89** [IgniteUI/igniteui-blazor#118]
## Description  
Describe the issue.

## Steps to reproduce  

1. Run sample
2. Use column chooser icon (top right)
3. Uncheck a column

## Result  
exception 

## Expected result  
igniteui-angular-elements.8178e307a7b3c266c3e4.bundle.js:1  Uncaught TypeError: Cannot read properties of undefined (reading 'toArray')
    at get columnChildren (igniteui-angular-elements.8178e307a7b3c266c3e4.bundle.js:1:888425)
    at h.getClone (app.b21fd74f6c640e6cbaa8.bundle.js:2:858319)
    at h.getClone (app.b21fd74f6c640e6cbaa8.bundle.js:2:858330)
    at h.replacerFunc (app.b21fd74f6c640e6cbaa8.bundle.js:2:859767)
    at Object.<anonymous> (app.b21fd74f6c640e6cbaa8.bundle.js:2:859950)
    at JSON.stringify (<anonymous>)
    at h.stringify (app.b21fd74f6c640e6cbaa8.bundle.js:2:859914)
    at R (app.b21fd74f6c640e6cbaa8.bundle.js:2:869007)
    at app.b21fd74f6c640e6cbaa8.bundle.js:2:870919
    at s.<computed> (igniteui-angular-elements.8178e307a7b3c266c3e4.bundle.js:1:29482)

## Attachments  
[column-hiding-options (column visibility events).zip](https://github.com/user-attachments/files/15515374/column-hiding-options.column.visibility.events.zip)

**Comment by mddifilippo89** [comment]
New issue has arised and old issue no longer occurs in B

Uncaught TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Object'
    |     property 'cdr' -> object with constructor 'Object'
    |     property 'value' -> object with constructor 'Object'
    |     property 'context' -> object with constructor 'Object'
    --- property 'value' closes the circle
    at JSON.stringify (<anonymous>)
    at h.stringify (app.025a647ac752ee98700f.bundle.js:2:901195)
    at R (app.025a647ac752ee98700f.bundle.js:2:910349)
    at app.025a647ac752ee98700f.bundle.js:2:912308
    at s.<computed> (igniteui-angular-elements.852df829b3175b4568ca.bundle.js:1:12317)
    at s.invokeTask (igniteui-angular-elements.852df829b3175b4568ca.bundle.js:1:20950)
    at e.runTask (igniteui-angular-elements.852df829b3175b4568ca.bundle.js:1:16264)
    at invokeTask (igniteui-angular-elements.852df829b3175b4568ca.bundle.js:1:22021)
    at n.useG.invoke (igniteui-angular-elements.852df829b3175b4568ca.bundle.js:1:21923)
    at i.args.<computed> (igniteui-angular-elements.852df829b3175b4568ca.bundle.js:1:11947)



![Image](https://github.com/user-attachments/assets/51d59518-733a-4024-be98-731d1ab03a46)
