### ISSUE TITLE
IgbDialog -  Unhandled exception rendering component: String 'System.Collections.Generic.Dictionary`2[System.String,System.Object]' was not recognized as a valid Boolean.

### ISSUE THREAD

**Issue by mddifilippo89** [IgniteUI/igniteui-blazor#140]
24.1.52

![image](https://github.com/user-attachments/assets/63105100-9d63-46ca-8ca6-affa1bb09226)

Microsoft.AspNetCore.Components.WebAssembly.Rendering.
[overview.zip](https://github.com/user-attachments/files/17249169/overview.zip)
WebAssemblyRenderer[100]
      Unhandled exception rendering component: String 'System.Collections.Generic.Dictionary`2[System.String,System.Object]' was not recognized as a valid Boolean.
System.FormatException: String 'System.Collections.Generic.Dictionary`2[System.String,System.Object]' was not recognized as a valid Boolean.
   at System.Boolean.Parse(ReadOnlySpan`1 value)
   at System.Boolean.Parse(String value)
   at IgniteUI.Blazor.Controls.BaseRendererControl.ReturnToBoolean(Object val)
   at IgniteUI.Blazor.Controls.IgbDialog.ShowAsync()
   at Infragistics.Samples.App.OnDialogShow() in C:\Users\mdifilippo.INFRAGISTICS\Documents\GitHub\igniteui-blazor-examples\samples\notifications\dialog\overview\App.razor:line 19
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)

**Comment by ChronosSF** [comment]
Doesn't reproduce in latest version.
